<?php
session_start();

print "<!DOCTYPE html>\n";
print "\n";
print "<html lang=\"en\">\n";
print "\n";
print "<head>\n";
print "    <meta charset=\"utf-8\" />\n";
print "    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"../assets/img/apple-icon.png\">\n";
print "    <link rel=\"icon\" type=\"image/png\" href=\"../assets/img/favicon.ico\">\n";
print "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n";
print "    <title>Light Bootstrap Dashboard - Free Bootstrap 4 Admin Dashboard by Creative Tim</title>\n";
print "    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\n";
print "    <!--     Fonts and icons     -->\n";
print "    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700,200\" rel=\"stylesheet\" />\n";
print "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\" />\n";
print "    <!-- CSS Files -->\n";
print "    <link href=\"../assets/css/bootstrap.min.css\" rel=\"stylesheet\" />\n";
print "    <link href=\"../assets/css/light-bootstrap-dashboard.css?v=2.0.0 \" rel=\"stylesheet\" />\n";
print "    <!-- CSS Just for demo purpose, don't include it in your project -->\n";
print "    <link href=\"../assets/css/demo.css\" rel=\"stylesheet\" />\n";
print "</head>\n";
print "\n";
print "<body>\n";
print "    <div class=\"wrapper\">\n";
print "        <div class=\"sidebar\" data-image=\"../assets/img/sidebar-5.jpg\">\n";
print "           \n";
print "            <div class=\"sidebar-wrapper\">\n";
print "                <div class=\"logo\">\n";
print "                    <a href=\"#pablo\" class=\"simple-text\">\n";
print "                        Delivery SLC (ADMIN)\n";
echo $_SESSION['user'];
print "                    </a>\n";
print "                </div>\n";
print "                <ul class=\"nav\">\n";
print "                    <li class=\"nav-item \">\n";
print "                        <a class=\"nav-link\" href=\"empresagestion.php\">\n";
print "                            <i class=\"nc-icon nc-chart-pie-35\"></i>\n";
print "                            <p>Gestion de Empresas</p>\n";
print "                        </a>\n";
print "                    </li>\n";
print "                    <li>\n";
print "                        <a class=\"nav-link\" href=\"./user.html\">\n";
print "                            <i class=\"nc-icon nc-circle-09\"></i>\n";
print "                            <p>Gestion de Usuarios</p>\n";
print "                        </a>\n";
print "                    </li>\n";
print "                    <li>\n";
print "                        <a class=\"nav-link\" href=\"./useradmin.php\">\n";
print "                            <i class=\"nc-icon nc-circle-09\"></i>\n";
print "                            <p>Gestion de ADMIN</p>\n";
print "                        </a>\n";
print "                    </li>\n";
print "                    <li>\n";
print "                        <a class=\"nav-link\" href=\"./maps.html\">\n";
print "                            <i class=\"nc-icon nc-pin-3\"></i>\n";
print "                            <p>Delivery</p>\n";
print "                        </a>\n";
print "                    </li>\n";
print "                    <li class=\"nav-item active active-pro\">\n";
print "                        <a class=\"nav-link active\" href=\"upgrade.html\">\n";
print "                            <i class=\"nc-icon nc-alien-33\"></i>\n";
print "                            <p>Upgrade to PRO</p>\n";
print "                        </a>\n";
print "                    </li>\n";
print "                </ul>\n";
print "            </div>\n";
print "        </div>\n";
print "        <div class=\"main-panel\">\n";
print "            <!-- Navbar -->\n";
print "            <nav class=\"navbar navbar-expand-lg \" color-on-scroll=\"500\">\n";
print "                <div class=\"container-fluid\">\n";
print "                    <a class=\"navbar-brand\" href=\"dashboardadmin.php\"> Gestion de Empresas </a>\n";
print "                    <button href=\"\" class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" aria-controls=\"navigation-index\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
print "                        <span class=\"navbar-toggler-bar burger-lines\"></span>\n";
print "                        <span class=\"navbar-toggler-bar burger-lines\"></span>\n";
print "                        <span class=\"navbar-toggler-bar burger-lines\"></span>\n";
print "                    </button>\n";
print "                    <div class=\"collapse navbar-collapse justify-content-end\" id=\"navigation\">\n";
print "                        <ul class=\"nav navbar-nav mr-auto\">\n";
print "                            <li class=\"nav-item\">\n";
print "                                <a href=\"#\" class=\"nav-link\" data-toggle=\"dropdown\">\n";
print "                                    <span class=\"d-lg-none\">Tablero</span>\n";
print "                                </a>\n";
print "                            </li>\n";
print "                        </ul>\n";
print "                        <ul class=\"navbar-nav ml-auto\">\n";
print "                            <li class=\"nav-item\">\n";
print "                                <a class=\"nav-link\" href=\"#pablo\">\n";
print "                                    <span class=\"no-icon\">Perfil</span>\n";
print "                                </a>\n";
print "                            </li>\n";
print "                           \n";
print "                            </li>\n";
print "                            <li class=\"nav-item\">\n";
print "                                <a class=\"nav-link\" href=\"adminlogin.php\">\n";
print "                                    <span class=\"no-icon\">Cerrar Sesion</span>\n";
print "                                </a>\n";
print "                            </li>\n";
print "                        </ul>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </nav>\n";
print "            <!-- End Navbar -->\n";
print "            <div class=\"content\">\n";
print "                <div class=\"container-fluid\">\n";
print "                    <div class=\"row\">\n";
print "                        <div class=\"col-md-12\">\n";
print "                            <div class=\"card strpied-tabled-with-hover\">\n";
print "                                <div class=\"card-header \">\n";
print "                                    <h4 class=\"card-title\">Lista de Empresas Inscritas a nuesto Delivery</h4>\n";
print "                                    <p class=\"card-category\">Delivery SLC</p>\n";
print "                                    <button onclick=\"location.href='RegistrarEmpresa.html'\" type=\"submit\" class=\"btn btn-info btn-fill pull-left\" >Registrar Nueva Empresa</button>\n";
print "                                </div>\n";
print "                                <div class=\"card-body table-full-width table-responsive\">\n";
print "                                    <table class=\"table table-hover table-striped\">\n";
print "                                        <thead>\n";
print "                                            <th>ID</th>\n";
print "                                            <th>Nombre-sucursal</th>\n";
print "                                            <th>Dirección</th>\n";
print "                                        </thead>\n";
print "                                        <tbody>\n";
print "                                            <tr>\n";
print "                                                <td>1</td>\n";
print "                                                <td>Pollos Kiky - Sub Banzer</td>\n";
print "                                                <td>Cuarto anillo Av. Banzer, mall Brisas </td>\n";
print "                                                <td class=\"td-actions text-right\">\n";
print "                                                    <button type=\"button\" rel=\"tooltip\" title=\"Editar\" class=\"btn btn-info btn-simple btn-link\">\n";
print "                                                        <i class=\"fa fa-edit\"></i>\n";
print "                                                    </button>\n";
print "                                                    <button type=\"button\" rel=\"tooltip\" title=\"Eliminar\" class=\"btn btn-danger btn-simple btn-link\">\n";
print "                                                        <i class=\"fa fa-times\"></i>\n";
print "                                                    </button>\n";
print "                                                </td>\n";
print "                                            </tr>\n";
print "                                            <tr>\n";
print "                                                <td>2</td>\n";
print "                                                <td>Pollos Kiky - Sub Banzer</td>\n";
print "                                                <td>Cuarto anillo Av. Banzer, mall Brisas </td>\n";
print "                                                <td class=\"td-actions text-right\">\n";
print "                                                    <button type=\"button\" rel=\"tooltip\" title=\"Editar\" class=\"btn btn-info btn-simple btn-link\">\n";
print "                                                        <i class=\"fa fa-edit\"></i>\n";
print "                                                    </button>\n";
print "                                                    <button type=\"button\" rel=\"tooltip\" title=\"Eliminar\" class=\"btn btn-danger btn-simple btn-link\">\n";
print "                                                        <i class=\"fa fa-times\"></i>\n";
print "                                                    </button>\n";
print "                                                </td>\n";
print "                                            </tr>\n";
print "                                            <tr>\n";
print "                                                <td>3</td>\n";
print "                                                <td>Pollos Kiky - Sub Banzer</td>\n";
print "                                                <td>Cuarto anillo Av. Banzer, mall Brisas </td>\n";
print "                                                <td class=\"td-actions text-right\">\n";
print "                                                    <button type=\"button\" rel=\"tooltip\" title=\"Editar\" class=\"btn btn-info btn-simple btn-link\">\n";
print "                                                        <i class=\"fa fa-edit\"></i>\n";
print "                                                    </button>\n";
print "                                                    <button type=\"button\" rel=\"tooltip\" title=\"Eliminar\" class=\"btn btn-danger btn-simple btn-link\">\n";
print "                                                        <i class=\"fa fa-times\"></i>\n";
print "                                                    </button>\n";
print "                                                </td>\n";
print "                                            </tr>\n";
print "                                            <tr>\n";
print "                                                <td>4</td>\n";
print "                                                <td>Pollos Kiky - Sub Banzer</td>\n";
print "                                                <td>Cuarto anillo Av. Banzer, mall Brisas </td>\n";
print "                                                <td class=\"td-actions text-right\">\n";
print "                                                    <button type=\"button\" rel=\"tooltip\" title=\"Editar\" class=\"btn btn-info btn-simple btn-link\">\n";
print "                                                        <i class=\"fa fa-edit\"></i>\n";
print "                                                    </button>\n";
print "                                                    <button type=\"button\" rel=\"tooltip\" title=\"Eliminar\" class=\"btn btn-danger btn-simple btn-link\">\n";
print "                                                        <i class=\"fa fa-times\"></i>\n";
print "                                                    </button>\n";
print "                                                </td>\n";
print "                                            </tr>\n";
print "                                        </tbody>\n";
print "                                    </table>\n";
print "                                </div>\n";
print "                            </div>\n";
print "                        </div>\n";
print "                    </div>\n";
print "                </div>\n";
print "            </div>\n";
print "            <footer class=\"footer\">\n";
print "                <div class=\"container-fluid\">\n";
print "                    <nav>\n";
print "                        <p class=\"copyright text-center\">\n";
print "                            ©\n";
print "                            <script>\n";
print "                                document.write(new Date().getFullYear())\n";
print "                            </script>\n";
print "                            <a href=\"dashboard.html\">Landing Web</a>, la mejor empresa de desarrollo web.\n";
print "                        </p>\n";
print "                    </nav>\n";
print "                </div>\n";
print "            </footer>\n";
print "        </div>\n";
print "    </div>";
print "    </html>";
?>
